### ISSUE TITLE
Proper summary of the project is Missing

### ISSUE THREAD

**Issue by rahultiwari56** [khrlimam/res-facenet#1]
You haven't mentioned about input size and other things required for using this pretrained model

**Comment by khrlimam** [comment]
Yea, thanks for pointing that out. I added basic info on how to use this model for inference. If you want to read more detail about the model you can refer to [this paper](https://github.com/khrlimam/skripsi/blob/master/pdfs/Jurnal%20Skripsi-Hairul%20Imam-en.pdf). For resume, this model uses modified resnet-50 so the inputs and the normalization mean and std are pretty much the same with original one. For details on how to train and prepare the dataset you can refer to [this repo](https://github.com/khrlimam/facenet). As this repo is originally intended as a package only so i dont add details here.
